name: Deploy to GitHub Pages and Deploy PR Preview
author: WATAHIKI Yuto
description: Deploy to GitHub Pages and deploy pull request preview using GitHub Actions

runs:
  using: composite
  steps:
    - name: Get Current Time for Key
      id: get-current-time
      run: echo "current_time=$(/bin/date -u "+%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Previous Artifact
      uses: actions/cache/restore@v3
      with:
        key: github-pages-${{ steps.get-current-time.outputs.current_time }}
        restore-keys: |
          github-pages-
        path: deploy_temp

    - name: Determine Where to Download Artifact
      id: download-path
      uses: actions/github-script@v6
      with:
        script: |
          const basePath = "deploy_temp";
          const githubEventName = "${{ github.event_name }}"; // "push" or "pull_request"
          if (githubEventName === "push") {
            const githubBranchName = "${{ github.ref_name }}";
            if (githubBranchName === "main" || githubBranchName === "master") {
              return basePath;
            }
            return `${basePath}/${githubBranchName}`;
          } else if (githubEventName === "pull_request") {
            const githubPullRequestNumber = "${{ github.event.number }}"; // <pr-number>
            return `${basePath}/pr-preview/pr-${githubPullRequestNumber}`;
          }
        result-encoding: string

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: github-pages
        path: artifact_temp

    - name: Extract Artifact
      run: cd artifact_temp/ && tar -xvf artifact.tar && ls -la
      shell: bash
    - run: mv artifact_temp/* ${{ steps.download-path.outputs.result }}
      shell: bash

    - name: Save Artifact for Next Run
      uses: actions/cache/save@v3
      with:
        key: github-pages-${{ steps.get-current-time.outputs.current_time }}
        path: deploy_temp

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: deploy_temp

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
