name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages
          path: deploy_temp
      - name: Get Current Time
        id: get-time
        run: echo "time=$(/bin/date -u "+%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
        shell: bash
      #   - name: Create Temporary Directory
      #     run: mkdir -p deploy_temp
      #   - name: Move dist to Temporary Directory
      #     run: mv dist deploy_temp
      - name: Get Previous Artifact
        uses: actions/cache/restore@v3
        with:
          key: artifact-${{ steps.get-time.outputs.time }}
          restore-keys: |
            artifact-
          path: dist
      - name: Create New Artifact Directory
        run: mkdir -p dist/pr-preview/pr-${{ github.event.number }}
      - name: Copy Previous Artifact to New Artifact Directory
        run: cp -r deploy_temp/* dist/pr-preview/pr-${{ github.event.number }}
      - name: Save Artifact for Next Run
        uses: actions/cache/save@v3
        with:
          key: artifact-${{ steps.get-time.outputs.time }}
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
