name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  pull_request:

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
      - name: Get time
        id: get-time
        run: echo "time=$(/bin/date -u "+%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
        shell: bash
      - run: mv dist out
      - run: ls
      - run: ls out
      - uses: actions/cache/restore@v3
        with:
          key: artifact-${{ steps.get-time.outputs.time }}
          restore-keys: |
            artifact-
          path: dist
      - run: ls
      - run: mkdir -p dist/${{ github.event.number }}
      - run: cp -r out/* dist/${{ github.event.number }}
      - run: ls
      - run: ls dist
      - run: ls dist/${{ github.event.number }}
      - uses: actions/cache/save@v3
        with:
          key: build-${{ steps.get-time.outputs.time }}
          path: dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
